#!/bin/sh
#PBS -l nodes=compute-0-0:ppn=32+compute-0-1:ppn=32+compute-0-2:ppn=32+compute-0-3:ppn=16+compute-0-4:ppn=16+compute-0-5:ppn=16+compute-0-6:ppn=16+compute-0-7:ppn=16
cd $PBS_O_WORKDIR
cat $PBS_NODEFILE > nodes
NO_OF_CORES=`cat $PBS_NODEFILE | egrep -v '^#'\|'^$' | wc -l | awk '{print $1}'`
echo $NO_OF_CORES
NODE_LIST=`cat $PBS_NODEFILE`
echo $NODE_LIST
~/opt/anaconda3/bin/mpiexec -np $NO_OF_CORES -machinefile nodes ~/opt/anaconda3/bin/python3 driver.py
